
spring:
  application:
    name: sazzler-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/sazzler_postgress_db
    username: amodhyh
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: "auth"

server:
  port: 8082
jwt:
  secret: 27f9bcfc4523599275abbb317f7117e8e864e7f31c2198c45df93f6c2d1a9ce7
  expiration: 3600000 # (1 hour)

eureka:
  instance:
    prefer-ip-address: true #register with IP address with the eureka server
  client:
    service-url:
        defaultZone: http://amodhyh:1234@localhost:8761/eureka/
logging:
  level:
    org:
        springframework:
            security: DEBUG

#prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    prometheus:
      enabled: true